# font
font_family Iosevka Nerd Font
font_size 14

# window
window_padding_width 12

# tab bar
tab_bar_style separator

tab_bar_margin_width 0
tab_bar_margin_height 0

tab_bar_min_tabs 1
tab_bar_padding 0 0
tab_separator ""

active_tab_background #3c3836
active_tab_foreground #ebdbb2

inactive_tab_background #504945
inactive_tab_foreground #a89984

tab_bar_background #282828

active_tab_font_style bold
inactive_tab_font_style normal

tab_title_template '   [{index}] {title}   '

# theme
include themes/gruvbox-dark-hard.conf

# keybinds
map ctrl+l clear_terminal scroll active
