input {
  kb_layout = pl
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =

  follow_mouse = 1

  repeat_delay = 500
  repeat_rate = 30
}

device {
  name = sinowealth-wired-gaming-mouse
  accel_profile = flat
  sensitivity = 0.25
}
