#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
pgrep -x polybar > /dev/null || polybar &

bspc monitor -d browse code term music chat extra extra

bspc config border_width 1
bspc config window_gap 0

bspc config focused_border_color "#9BA19B"
bspc config normal_border_color "#404540"

bspc config focus_follows_pointer true
